$axure.loadCurrentPage({
  "url":"detail_2.html",
  "generationDate":new Date(1398849772556.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/home/bg.png",
    "width":640,
    "height":240},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"467a6b1278f84399ba17914186a9577c",
    "type":"Axure:Page",
    "name":"detail 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec28d828f8384d3c8a163017fa63e33c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5755cb1b8f714c0196595fad1572149a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u0.png"}},
{
          "id":"53725bbacf6f432390b924286fffffb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":640,
              "height":679}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d414e526aab4d3a88f2b26e78affd6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":640,
                  "height":679}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u2.png"}},
{
          "id":"181aaf57445d42948ca57a37a7babbe3",
          "label":"DT",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":480,
              "height":289}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onShow":{
              "description":"OnShow",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT1 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT2 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT3 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT4 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 DT",
                      "objectsToFades":[{
                          "objectPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onHide":{
              "description":"OnHide",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 DT",
                      "objectsToFades":[{
                          "objectPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT1 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT2 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT3 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT4 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 DT",
                      "objectsToFades":[{
                          "objectPath":["181aaf57445d42948ca57a37a7babbe3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8212e3eae6fa4191bf7d4a42778abd15",
              "label":"DT1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"455b96dac40b4c07ab0c173828c7a195",
                  "label":"",
                  "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc85614c67a54f4b910903aba41d70ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_2/u5.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"5220d7c478b74c909656f374fd3a5764",
              "label":"DT2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7fc79ddfbeb9489399da42ad840176c7",
                  "label":"",
                  "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93feffa92223404ebb3d6531b2b0cbe8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_2/u7.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"8c1a725d3d354f2290aa78394bfe0a8d",
              "label":"DT3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e2a6a31359a4458488e42c382613fa27",
                  "label":"",
                  "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7b0888de3fc4497b898d948abbd82bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_2/u9.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ca0334d4aba346eaab29b7bf892422a1",
              "label":"DT4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7ac5453ddd9a4741a794858a7ebdf036",
                  "label":"",
                  "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"729894f3aef94e0d89cb5d7d199ed976",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"181aaf57445d42948ca57a37a7babbe3",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_2/u11.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a8e4b3999d5c40fbb35e1b7ae17c125a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":419},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e325873ff4d345f6bd7b1ec482d5c70d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":419},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_2/u13.png"}},
{
          "id":"14a5b8bfe4f94dac90c97de2f334bcbd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":399},
            "size":{
              "width":563,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detail_1/u15_line.png"}},
{
          "id":"894069a2b1be4751989051dc4feb89b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":423},
            "size":{
              "width":330,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e7a95470964b4b8bd33a0bcb9679d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":423},
                "size":{
                  "width":330,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbed3796ef8d41958238aaf8008cb8a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":542},
            "size":{
              "width":510,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b95b260871b24b6b910280b04c6dc1ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":542},
                "size":{
                  "width":510,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fb382c299d54c0d895b9aa87e100f32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":700},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a442609b44b14f51aa194b8516041b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":700},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcmyz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcmyz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"9e50729505b84f0c925b3bf0a67f45a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":14},
            "size":{
              "width":385,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dbc5550b3f547c0b3214fabf1734ad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":14},
                "size":{
                  "width":385,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e9d701f0fad4120bd4a7750457200ce",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseDown":{
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":16,
              "y":10},
            "size":{
              "width":74,
              "height":60},
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64f69c43d5c74483a04a79fcf31780f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseDown":{
                    "outerShadow":{
                      "on":false,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":16,
                  "y":10},
                "size":{
                  "width":74,
                  "height":60},
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detail_1/button_u24.png",
            "mouseDown~":"images/detail_1/button_u24_mouseDown.png"}},
{
          "id":"d7fb25af9a954be99738424079a4dfab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":700},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"688b8173fb6b48229b7a1f987f44e290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":700},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"3fb201cce1b14d95a00602b187101838",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":700},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5872db9a70f24f89810ea981484c13ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":700},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec28d828f8384d3c8a163017fa63e33c":{
      "scriptId":"u0"},
    "5755cb1b8f714c0196595fad1572149a":{
      "scriptId":"u1"},
    "53725bbacf6f432390b924286fffffb4":{
      "scriptId":"u2"},
    "9d414e526aab4d3a88f2b26e78affd6c":{
      "scriptId":"u3"},
    "181aaf57445d42948ca57a37a7babbe3":{
      "scriptId":"u4"},
    "455b96dac40b4c07ab0c173828c7a195":{
      "scriptId":"u5"},
    "cc85614c67a54f4b910903aba41d70ec":{
      "scriptId":"u6"},
    "7fc79ddfbeb9489399da42ad840176c7":{
      "scriptId":"u7"},
    "93feffa92223404ebb3d6531b2b0cbe8":{
      "scriptId":"u8"},
    "e2a6a31359a4458488e42c382613fa27":{
      "scriptId":"u9"},
    "c7b0888de3fc4497b898d948abbd82bb":{
      "scriptId":"u10"},
    "7ac5453ddd9a4741a794858a7ebdf036":{
      "scriptId":"u11"},
    "729894f3aef94e0d89cb5d7d199ed976":{
      "scriptId":"u12"},
    "a8e4b3999d5c40fbb35e1b7ae17c125a":{
      "scriptId":"u13"},
    "e325873ff4d345f6bd7b1ec482d5c70d":{
      "scriptId":"u14"},
    "14a5b8bfe4f94dac90c97de2f334bcbd":{
      "scriptId":"u15"},
    "894069a2b1be4751989051dc4feb89b9":{
      "scriptId":"u16"},
    "56e7a95470964b4b8bd33a0bcb9679d8":{
      "scriptId":"u17"},
    "dbed3796ef8d41958238aaf8008cb8a4":{
      "scriptId":"u18"},
    "b95b260871b24b6b910280b04c6dc1ed":{
      "scriptId":"u19"},
    "6fb382c299d54c0d895b9aa87e100f32":{
      "scriptId":"u20"},
    "a442609b44b14f51aa194b8516041b70":{
      "scriptId":"u21"},
    "9e50729505b84f0c925b3bf0a67f45a4":{
      "scriptId":"u22"},
    "2dbc5550b3f547c0b3214fabf1734ad2":{
      "scriptId":"u23"},
    "1e9d701f0fad4120bd4a7750457200ce":{
      "scriptId":"u24"},
    "64f69c43d5c74483a04a79fcf31780f7":{
      "scriptId":"u25"},
    "d7fb25af9a954be99738424079a4dfab":{
      "scriptId":"u26"},
    "688b8173fb6b48229b7a1f987f44e290":{
      "scriptId":"u27"},
    "3fb201cce1b14d95a00602b187101838":{
      "scriptId":"u28"},
    "5872db9a70f24f89810ea981484c13ff":{
      "scriptId":"u29"}}});