$axure.loadCurrentPage({
  "url":"detail_5.html",
  "generationDate":new Date(1398849772887.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/home/bg.png",
    "width":640,
    "height":240},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"81ecd10d74cc47908489e6fff5877fc8",
    "type":"Axure:Page",
    "name":"detail 5",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b0f949044c54f40a8b3c20a400b9cd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e54c26c3d1534530a9c1955fbe951455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u0.png"}},
{
          "id":"b16fad8db92c4431b648d9bc54d54f98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":640,
              "height":613}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fdf41d789f54e8991f0adc25af54be5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":640,
                  "height":613}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u2.png"}},
{
          "id":"0abbc1205db744aebfb199777fe11d74",
          "label":"DT",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":480,
              "height":289}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onShow":{
              "description":"OnShow",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT1 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT2 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT3 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT4 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 DT",
                      "objectsToFades":[{
                          "objectPath":["0abbc1205db744aebfb199777fe11d74"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onHide":{
              "description":"OnHide",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 DT",
                      "objectsToFades":[{
                          "objectPath":["0abbc1205db744aebfb199777fe11d74"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT1 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT2 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT3 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT4 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["0abbc1205db744aebfb199777fe11d74"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 DT",
                      "objectsToFades":[{
                          "objectPath":["0abbc1205db744aebfb199777fe11d74"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f6fd59b473084cab8fec5e32564d466e",
              "label":"DT1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5a7d57bb328b42bbbd157b2faeac2b0b",
                  "label":"",
                  "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74a8b9c84c9f4279a68ebcb21e9d679b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_5/u5.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e0f146b958b14410ab9d5994bc1008f3",
              "label":"DT2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c2307f13354847019be9109b02ada965",
                  "label":"",
                  "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"054c586c3cd44c6ea5a39d914f3de726",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_5/u7.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"dd1077bcc8d14891ac904cb8737966e4",
              "label":"DT3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0356d52b5a8d4a4c882cf177c155e264",
                  "label":"",
                  "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6275844897764577b96465746fa96eeb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_5/u9.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"7b38fdd634a84f65ae5c1d1eca72a5c7",
              "label":"DT4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"797009ce9bc84e32b0c8bbcd5517e933",
                  "label":"",
                  "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7fc1225016e4586918892b9efc17737",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0abbc1205db744aebfb199777fe11d74",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_5/u11.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e3315b80ee73421cad0c0d6ce55ab7b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":419},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c042db724214b5b98ed1c24ad82aa85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":419},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_5/u13.png"}},
{
          "id":"bca15b09500a422eadb191ff8b0f01a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":399},
            "size":{
              "width":563,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detail_1/u15_line.png"}},
{
          "id":"0d25540d8b99446ab3e36634ea0e93ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":423},
            "size":{
              "width":270,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f0f53826ea64f54b19839ca1a616d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":423},
                "size":{
                  "width":270,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"915168aaa4cd46539fa49fb110e4443c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":529},
            "size":{
              "width":510,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46a54a0984ed48c989556d11f29338db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":529},
                "size":{
                  "width":510,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdbcf2055ee9426badebb3e58f50fbd3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":634},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815808927aa24c808f8e9bdd2fd61997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":634},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlssyz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlssyz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"2aad5e10051443e084459c3b49947d08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":696},
            "size":{
              "width":640,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6a24db496946a6904475d2d4b549d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":696},
                "size":{
                  "width":640,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u34.png"}},
{
          "id":"56290813b52848bb9027a79066e11a9b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":32,
              "y":725},
            "size":{
              "width":577,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18d89ebaf52400badbe9fd16a005aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":32,
                  "y":725},
                "size":{
                  "width":577,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e21c2a3b8cc44b24bb97e6549a4f9e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":128,
              "y":12},
            "size":{
              "width":385,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3a612e13eb4351b31ea9a5219ce30d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":12},
                "size":{
                  "width":385,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"207cc2aab4b44fd7ba3110e01c6fced6",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseDown":{
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":16,
              "y":10},
            "size":{
              "width":74,
              "height":60},
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df4e52a473384f169db7bfcf7deb4b6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseDown":{
                    "outerShadow":{
                      "on":false,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":16,
                  "y":10},
                "size":{
                  "width":74,
                  "height":60},
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detail_1/button_u24.png",
            "mouseDown~":"images/detail_1/button_u24_mouseDown.png"}},
{
          "id":"5e5a1082ce0c4254810c0c55ccdef0fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":634},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3341fabf0da41ddb6959299ce932bb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":634},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"f2b82930f292420194d8e726da61d6d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":634},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ad2276b2bc4eb38f9a99ba4a69dd60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":634},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3b0f949044c54f40a8b3c20a400b9cd4":{
      "scriptId":"u0"},
    "e54c26c3d1534530a9c1955fbe951455":{
      "scriptId":"u1"},
    "b16fad8db92c4431b648d9bc54d54f98":{
      "scriptId":"u2"},
    "4fdf41d789f54e8991f0adc25af54be5":{
      "scriptId":"u3"},
    "0abbc1205db744aebfb199777fe11d74":{
      "scriptId":"u4"},
    "5a7d57bb328b42bbbd157b2faeac2b0b":{
      "scriptId":"u5"},
    "74a8b9c84c9f4279a68ebcb21e9d679b":{
      "scriptId":"u6"},
    "c2307f13354847019be9109b02ada965":{
      "scriptId":"u7"},
    "054c586c3cd44c6ea5a39d914f3de726":{
      "scriptId":"u8"},
    "0356d52b5a8d4a4c882cf177c155e264":{
      "scriptId":"u9"},
    "6275844897764577b96465746fa96eeb":{
      "scriptId":"u10"},
    "797009ce9bc84e32b0c8bbcd5517e933":{
      "scriptId":"u11"},
    "a7fc1225016e4586918892b9efc17737":{
      "scriptId":"u12"},
    "e3315b80ee73421cad0c0d6ce55ab7b2":{
      "scriptId":"u13"},
    "1c042db724214b5b98ed1c24ad82aa85":{
      "scriptId":"u14"},
    "bca15b09500a422eadb191ff8b0f01a2":{
      "scriptId":"u15"},
    "0d25540d8b99446ab3e36634ea0e93ab":{
      "scriptId":"u16"},
    "7f0f53826ea64f54b19839ca1a616d47":{
      "scriptId":"u17"},
    "915168aaa4cd46539fa49fb110e4443c":{
      "scriptId":"u18"},
    "46a54a0984ed48c989556d11f29338db":{
      "scriptId":"u19"},
    "cdbcf2055ee9426badebb3e58f50fbd3":{
      "scriptId":"u20"},
    "815808927aa24c808f8e9bdd2fd61997":{
      "scriptId":"u21"},
    "2aad5e10051443e084459c3b49947d08":{
      "scriptId":"u22"},
    "fb6a24db496946a6904475d2d4b549d4":{
      "scriptId":"u23"},
    "56290813b52848bb9027a79066e11a9b":{
      "scriptId":"u24"},
    "f18d89ebaf52400badbe9fd16a005aec":{
      "scriptId":"u25"},
    "e21c2a3b8cc44b24bb97e6549a4f9e08":{
      "scriptId":"u26"},
    "1e3a612e13eb4351b31ea9a5219ce30d":{
      "scriptId":"u27"},
    "207cc2aab4b44fd7ba3110e01c6fced6":{
      "scriptId":"u28"},
    "df4e52a473384f169db7bfcf7deb4b6b":{
      "scriptId":"u29"},
    "5e5a1082ce0c4254810c0c55ccdef0fc":{
      "scriptId":"u30"},
    "a3341fabf0da41ddb6959299ce932bb5":{
      "scriptId":"u31"},
    "f2b82930f292420194d8e726da61d6d6":{
      "scriptId":"u32"},
    "11ad2276b2bc4eb38f9a99ba4a69dd60":{
      "scriptId":"u33"}}});