$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1398849772164.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/home/bg.png",
    "width":640,
    "height":240},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"0e1ceecfdfeb480986ff62c46deb9cf3",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"de3105bed8de44829f33abc8d9c6eadc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":640,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1401c75058424cd89809370537051c3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":640,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 1",
                      "target":{
                        "targetType":"page",
                        "url":"detail_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"ef60ee0bb36b4395a08dfc4a3c2c70cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":102},
            "size":{
              "width":177,
              "height":177}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7108199c084c16a5b2ff3c0c6c02f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":102},
                "size":{
                  "width":177,
                  "height":177}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"22c22807c9ae44e4a0a3d6cac39c6c03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75cee53c5954a60a1cdac729e4b6496",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"24876041cfb149298bb47823ef0ef01a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":355},
            "size":{
              "width":640,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b65bce2e6c748f9afdfe2c5a83a97f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":355},
                "size":{
                  "width":640,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 2",
                      "target":{
                        "targetType":"page",
                        "url":"detail_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"e8c9f8b6b4a4407fba6a2235983a778b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":377},
            "size":{
              "width":177,
              "height":177}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7c5e41b9544a6fb0087c3f832abf1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":377},
                "size":{
                  "width":177,
                  "height":177}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"eceb5f71def6466a99a05e20b6bccbbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":577},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a0c29faa13406d977a1e1ba741f256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":577},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"a7fa772ee415426cadcbf81fdbf77fb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":292},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9ef3b066d5f44e080b60b5aaf3f6fd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":292},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=lsyz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=lsyz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"9f963e0a3e38432f9ba56ef3389a0fb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":640},
            "size":{
              "width":640,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a00717bd6a84f53934cca7eba28d5ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":640},
                "size":{
                  "width":640,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 3",
                      "target":{
                        "targetType":"page",
                        "url":"detail_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"104aeb2fd2ab4a8f87445a1e8fdc3258",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":662},
            "size":{
              "width":177,
              "height":177}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6bb04556cb34952a855d2160e1744f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":662},
                "size":{
                  "width":177,
                  "height":177}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"76704e7ed4d04f329293f11e8f2d1c9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":862},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c6d30a210504dc097378810678e1451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":862},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"b17c62fba0324e83b19de8d00cb97fda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":925},
            "size":{
              "width":640,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7819861361eb4cb180818c9bd599e7a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":925},
                "size":{
                  "width":640,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 4",
                      "target":{
                        "targetType":"page",
                        "url":"detail_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"f24199c7bad94db980f9bc046f4445b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":947},
            "size":{
              "width":177,
              "height":177}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"130a1130ea624ef0a93772244cc00c97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":947},
                "size":{
                  "width":177,
                  "height":177}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"583fc9dca5eb4fe2aad0a339f319e754",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":1147},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fbc9c257a174e0cb50b9c345eacd639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":1147},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"466fdd13228a429faebff6ebc8291712",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1210},
            "size":{
              "width":640,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f52d0a3e9940dc83b71de0ec42b57a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1210},
                "size":{
                  "width":640,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 5",
                      "target":{
                        "targetType":"page",
                        "url":"detail_5.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"82b022e73e224c198e1435783c9f0b60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":1232},
            "size":{
              "width":177,
              "height":177}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e93324fa3c8a4e67a8a423365ee77094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":1232},
                "size":{
                  "width":177,
                  "height":177}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"0cc626e73185475a9141021b21828f29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":1432},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9630f1bd61ce407384300b95882f5036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":1432},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"7972f5afe6654e1bbfa0d205815b9736",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":108},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd29b2af0eb4a1c9055b53303532e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":108},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 1",
                      "target":{
                        "targetType":"page",
                        "url":"detail_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u32.jpg"}},
{
          "id":"5c5829316e7842f8bc2d658d47e406d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1502},
            "size":{
              "width":640,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c80fc001ef74551b12e9eb92f2a0250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1502},
                "size":{
                  "width":640,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u34.png"}},
{
          "id":"a942908e166c4348b17e64750f8bfb5b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":33,
              "y":1530},
            "size":{
              "width":577,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b10ef60303e4a98ba574356825e7d9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":33,
                  "y":1530},
                "size":{
                  "width":577,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d7b31384c7a4000b576ca3dc4d59af0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "location":{
              "x":220,
              "y":108},
            "size":{
              "width":150,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c81320888d04d26984767b7a44446e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "location":{
                  "x":220,
                  "y":108},
                "size":{
                  "width":150,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 1",
                      "target":{
                        "targetType":"page",
                        "url":"detail_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f637b902e8724362aeccd1f7816b56ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":160},
            "size":{
              "width":353,
              "height":93},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e993667aafa34d64955c35cc2997bf7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":160},
                "size":{
                  "width":353,
                  "height":93},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 1",
                      "target":{
                        "targetType":"page",
                        "url":"detail_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a7b46e3dce944c9935b2746877c01a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "location":{
              "x":220,
              "y":383},
            "size":{
              "width":310,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af2fa5b008e645da92712d1eaa30ae30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "location":{
                  "x":220,
                  "y":383},
                "size":{
                  "width":310,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 2",
                      "target":{
                        "targetType":"page",
                        "url":"detail_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0da72bcb2afd424abfd1d0891177a9c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":435},
            "size":{
              "width":353,
              "height":93},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f04d96c7d3743b0b3d03276ff5665fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":435},
                "size":{
                  "width":353,
                  "height":93},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 2",
                      "target":{
                        "targetType":"page",
                        "url":"detail_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d29cc10d364c77934306f3fb52e330",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":577},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28fa3e3a02fd479ca48af763d44270ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":577},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcmyz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcmyz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"03f63909c4af484a8b933a60616eece5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":383},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8644b4bfde8645f4b6c8d80d3d499fb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":383},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 2",
                      "target":{
                        "targetType":"page",
                        "url":"detail_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u48.jpg"}},
{
          "id":"7bad133b17404085bd54abbcee73b321",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":669},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e41553887ca49d0a48e21d06d3f3fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":669},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 3",
                      "target":{
                        "targetType":"page",
                        "url":"detail_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u50.jpg"}},
{
          "id":"74b6f2c1cd414057815cdb63d1e1479d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "location":{
              "x":220,
              "y":669},
            "size":{
              "width":150,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e503d38603c4c49984b7431b8dd785d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "location":{
                  "x":220,
                  "y":669},
                "size":{
                  "width":150,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 3",
                      "target":{
                        "targetType":"page",
                        "url":"detail_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e49edafc71fd4b01b4863f46c77f8c86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":720},
            "size":{
              "width":353,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31c50d0edd04d6582124f0d8b5b4d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":720},
                "size":{
                  "width":353,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 3",
                      "target":{
                        "targetType":"page",
                        "url":"detail_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd395aabc5ab401cb101163de591a053",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":862},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d179aa348d6412da4e160c98da71705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":862},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=kxxxlyz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=kxxxlyz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"221df52e79114411b00dca37de4cdca2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":953},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3c537ad066a42599e0b3f278cc6f2f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":953},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 4",
                      "target":{
                        "targetType":"page",
                        "url":"detail_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u58.jpg"}},
{
          "id":"e4809f0239f64eceb20ba7a953565d84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":1147},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b15a5087099b4fae94767fb5659556fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":1147},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=py2yz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=py2yz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"eafd76dd434e4e01b81e692f0c085e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "location":{
              "x":220,
              "y":953},
            "size":{
              "width":192,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927fce685237412785c445babd76668c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "location":{
                  "x":220,
                  "y":953},
                "size":{
                  "width":192,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 4",
                      "target":{
                        "targetType":"page",
                        "url":"detail_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41bf072ae7814f24962b9e03b4813490",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":1004},
            "size":{
              "width":353,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b55f76a1046d4080948a9115fe554efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":1004},
                "size":{
                  "width":353,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 4",
                      "target":{
                        "targetType":"page",
                        "url":"detail_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99ae67f3e0f54e5ea722e88e83b1168a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":1239},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b6db42b16c42e3bea9fa1705efdaa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":1239},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 5",
                      "target":{
                        "targetType":"page",
                        "url":"detail_5.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u66.jpg"}},
{
          "id":"716e27f57d1d4f25854e4d27ab8304b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":1432},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a738a061b414a67af15f149860a138b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":1432},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlssyz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlssyz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"a08b43c4f4b744edacf53998bf9708af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "location":{
              "x":220,
              "y":1239},
            "size":{
              "width":280,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0370ce2b58bc4ee5b367b81ceb82ebe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "location":{
                  "x":220,
                  "y":1239},
                "size":{
                  "width":280,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 5",
                      "target":{
                        "targetType":"page",
                        "url":"detail_5.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7804d2e534241a4aa79e9ad5c4e0bbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":1295},
            "size":{
              "width":353,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77636ce95e96413395e329fe2aff21af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":1295},
                "size":{
                  "width":353,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 detail 5",
                      "target":{
                        "targetType":"page",
                        "url":"detail_5.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f4f0be00dd14cc19bec4de2231d1838",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":292},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1da18768f2ff4736ab160c1f403ea78d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":292},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=lhb_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=lhb_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"6fdd55808fc3423ab07667a005acb2f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":577},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f08c5b5a2cb49d7a75195103dc6b16f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":577},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"6b8dd9d1253742ca8418a01b8bafa0b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":577},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3196d8155ab946f5a1f937b0d5e4e78a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":577},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xcm_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"1f38cf982cef4066893ed8e78885b1c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":862},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be818ec9e934990988e325df2f8e044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":862},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xxl_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xxl_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"d50305f7e4f54762a311daa084a8a752",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":862},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c37c616a204945078eb21f635d2974ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":862},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=xxl_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=xxl_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"29122dee2acf4ea4a32efdedf8dd1248",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":1147},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a605a072133041c892835590e97427e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":1147},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"48bc61bf1a2d46aead021079a0e0e06a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":1147},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da2706e98be54b0eb049814241788ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":1147},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"99d61ce1204e42569279b465f036e676",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":1432},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241971e8f0fb4fb09b7b0607801e7dcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":1432},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"d4f3c29b24ec4a1e8f39f6200f234f55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":1432},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f39aed966b4c2fafd3d5152809d8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":1432},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=wlss_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "de3105bed8de44829f33abc8d9c6eadc":{
      "scriptId":"u0"},
    "1401c75058424cd89809370537051c3c":{
      "scriptId":"u1"},
    "ef60ee0bb36b4395a08dfc4a3c2c70cc":{
      "scriptId":"u2"},
    "7c7108199c084c16a5b2ff3c0c6c02f4":{
      "scriptId":"u3"},
    "22c22807c9ae44e4a0a3d6cac39c6c03":{
      "scriptId":"u4"},
    "d75cee53c5954a60a1cdac729e4b6496":{
      "scriptId":"u5"},
    "24876041cfb149298bb47823ef0ef01a":{
      "scriptId":"u6"},
    "8b65bce2e6c748f9afdfe2c5a83a97f1":{
      "scriptId":"u7"},
    "e8c9f8b6b4a4407fba6a2235983a778b":{
      "scriptId":"u8"},
    "df7c5e41b9544a6fb0087c3f832abf1b":{
      "scriptId":"u9"},
    "eceb5f71def6466a99a05e20b6bccbbe":{
      "scriptId":"u10"},
    "31a0c29faa13406d977a1e1ba741f256":{
      "scriptId":"u11"},
    "a7fa772ee415426cadcbf81fdbf77fb1":{
      "scriptId":"u12"},
    "f9ef3b066d5f44e080b60b5aaf3f6fd5":{
      "scriptId":"u13"},
    "9f963e0a3e38432f9ba56ef3389a0fb3":{
      "scriptId":"u14"},
    "9a00717bd6a84f53934cca7eba28d5ad":{
      "scriptId":"u15"},
    "104aeb2fd2ab4a8f87445a1e8fdc3258":{
      "scriptId":"u16"},
    "e6bb04556cb34952a855d2160e1744f3":{
      "scriptId":"u17"},
    "76704e7ed4d04f329293f11e8f2d1c9c":{
      "scriptId":"u18"},
    "5c6d30a210504dc097378810678e1451":{
      "scriptId":"u19"},
    "b17c62fba0324e83b19de8d00cb97fda":{
      "scriptId":"u20"},
    "7819861361eb4cb180818c9bd599e7a8":{
      "scriptId":"u21"},
    "f24199c7bad94db980f9bc046f4445b6":{
      "scriptId":"u22"},
    "130a1130ea624ef0a93772244cc00c97":{
      "scriptId":"u23"},
    "583fc9dca5eb4fe2aad0a339f319e754":{
      "scriptId":"u24"},
    "6fbc9c257a174e0cb50b9c345eacd639":{
      "scriptId":"u25"},
    "466fdd13228a429faebff6ebc8291712":{
      "scriptId":"u26"},
    "15f52d0a3e9940dc83b71de0ec42b57a":{
      "scriptId":"u27"},
    "82b022e73e224c198e1435783c9f0b60":{
      "scriptId":"u28"},
    "e93324fa3c8a4e67a8a423365ee77094":{
      "scriptId":"u29"},
    "0cc626e73185475a9141021b21828f29":{
      "scriptId":"u30"},
    "9630f1bd61ce407384300b95882f5036":{
      "scriptId":"u31"},
    "7972f5afe6654e1bbfa0d205815b9736":{
      "scriptId":"u32"},
    "bbd29b2af0eb4a1c9055b53303532e39":{
      "scriptId":"u33"},
    "5c5829316e7842f8bc2d658d47e406d6":{
      "scriptId":"u34"},
    "7c80fc001ef74551b12e9eb92f2a0250":{
      "scriptId":"u35"},
    "a942908e166c4348b17e64750f8bfb5b":{
      "scriptId":"u36"},
    "6b10ef60303e4a98ba574356825e7d9d":{
      "scriptId":"u37"},
    "1d7b31384c7a4000b576ca3dc4d59af0":{
      "scriptId":"u38"},
    "5c81320888d04d26984767b7a44446e1":{
      "scriptId":"u39"},
    "f637b902e8724362aeccd1f7816b56ec":{
      "scriptId":"u40"},
    "e993667aafa34d64955c35cc2997bf7c":{
      "scriptId":"u41"},
    "2a7b46e3dce944c9935b2746877c01a2":{
      "scriptId":"u42"},
    "af2fa5b008e645da92712d1eaa30ae30":{
      "scriptId":"u43"},
    "0da72bcb2afd424abfd1d0891177a9c6":{
      "scriptId":"u44"},
    "0f04d96c7d3743b0b3d03276ff5665fd":{
      "scriptId":"u45"},
    "b4d29cc10d364c77934306f3fb52e330":{
      "scriptId":"u46"},
    "28fa3e3a02fd479ca48af763d44270ac":{
      "scriptId":"u47"},
    "03f63909c4af484a8b933a60616eece5":{
      "scriptId":"u48"},
    "8644b4bfde8645f4b6c8d80d3d499fb4":{
      "scriptId":"u49"},
    "7bad133b17404085bd54abbcee73b321":{
      "scriptId":"u50"},
    "5e41553887ca49d0a48e21d06d3f3fc8":{
      "scriptId":"u51"},
    "74b6f2c1cd414057815cdb63d1e1479d":{
      "scriptId":"u52"},
    "7e503d38603c4c49984b7431b8dd785d":{
      "scriptId":"u53"},
    "e49edafc71fd4b01b4863f46c77f8c86":{
      "scriptId":"u54"},
    "e31c50d0edd04d6582124f0d8b5b4d12":{
      "scriptId":"u55"},
    "cd395aabc5ab401cb101163de591a053":{
      "scriptId":"u56"},
    "3d179aa348d6412da4e160c98da71705":{
      "scriptId":"u57"},
    "221df52e79114411b00dca37de4cdca2":{
      "scriptId":"u58"},
    "c3c537ad066a42599e0b3f278cc6f2f7":{
      "scriptId":"u59"},
    "e4809f0239f64eceb20ba7a953565d84":{
      "scriptId":"u60"},
    "b15a5087099b4fae94767fb5659556fc":{
      "scriptId":"u61"},
    "eafd76dd434e4e01b81e692f0c085e85":{
      "scriptId":"u62"},
    "927fce685237412785c445babd76668c":{
      "scriptId":"u63"},
    "41bf072ae7814f24962b9e03b4813490":{
      "scriptId":"u64"},
    "b55f76a1046d4080948a9115fe554efe":{
      "scriptId":"u65"},
    "99ae67f3e0f54e5ea722e88e83b1168a":{
      "scriptId":"u66"},
    "45b6db42b16c42e3bea9fa1705efdaa9":{
      "scriptId":"u67"},
    "716e27f57d1d4f25854e4d27ab8304b2":{
      "scriptId":"u68"},
    "0a738a061b414a67af15f149860a138b":{
      "scriptId":"u69"},
    "a08b43c4f4b744edacf53998bf9708af":{
      "scriptId":"u70"},
    "0370ce2b58bc4ee5b367b81ceb82ebe8":{
      "scriptId":"u71"},
    "d7804d2e534241a4aa79e9ad5c4e0bbc":{
      "scriptId":"u72"},
    "77636ce95e96413395e329fe2aff21af":{
      "scriptId":"u73"},
    "8f4f0be00dd14cc19bec4de2231d1838":{
      "scriptId":"u74"},
    "1da18768f2ff4736ab160c1f403ea78d":{
      "scriptId":"u75"},
    "6fdd55808fc3423ab07667a005acb2f2":{
      "scriptId":"u76"},
    "1f08c5b5a2cb49d7a75195103dc6b16f":{
      "scriptId":"u77"},
    "6b8dd9d1253742ca8418a01b8bafa0b3":{
      "scriptId":"u78"},
    "3196d8155ab946f5a1f937b0d5e4e78a":{
      "scriptId":"u79"},
    "1f38cf982cef4066893ed8e78885b1c1":{
      "scriptId":"u80"},
    "4be818ec9e934990988e325df2f8e044":{
      "scriptId":"u81"},
    "d50305f7e4f54762a311daa084a8a752":{
      "scriptId":"u82"},
    "c37c616a204945078eb21f635d2974ec":{
      "scriptId":"u83"},
    "29122dee2acf4ea4a32efdedf8dd1248":{
      "scriptId":"u84"},
    "a605a072133041c892835590e97427e2":{
      "scriptId":"u85"},
    "48bc61bf1a2d46aead021079a0e0e06a":{
      "scriptId":"u86"},
    "da2706e98be54b0eb049814241788ecb":{
      "scriptId":"u87"},
    "99d61ce1204e42569279b465f036e676":{
      "scriptId":"u88"},
    "241971e8f0fb4fb09b7b0607801e7dcb":{
      "scriptId":"u89"},
    "d4f3c29b24ec4a1e8f39f6200f234f55":{
      "scriptId":"u90"},
    "d8f39aed966b4c2fafd3d5152809d8ee":{
      "scriptId":"u91"}}});