$axure.loadCurrentPage({
  "url":"detail_4.html",
  "generationDate":new Date(1398849772807.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/home/bg.png",
    "width":640,
    "height":240},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"e4281120e49f482bb535ad2a2f28592d",
    "type":"Axure:Page",
    "name":"detail 4",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4782a96699394f8cabf07f86f51aeadb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80f850c5faf74d0fa8540f8f626c7504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u0.png"}},
{
          "id":"95f0260c725749f3aeab1c2e931e0d5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":640,
              "height":699}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca767d2567a94e4db6614561d9d558ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":640,
                  "height":699}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_1/u2.png"}},
{
          "id":"f9ebedf4ce7c4c928d02b8af8c0862f3",
          "label":"DT",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":480,
              "height":289}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onShow":{
              "description":"OnShow",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT1 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT2 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT3 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT4 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 DT",
                      "objectsToFades":[{
                          "objectPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onHide":{
              "description":"OnHide",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 DT",
                      "objectsToFades":[{
                          "objectPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT1 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT2 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT3 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"设置 DT 到 DT4 淡入淡出 in 500ms 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 DT",
                      "objectsToFades":[{
                          "objectPath":["f9ebedf4ce7c4c928d02b8af8c0862f3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d267f2acf10a414793adc430adde7da0",
              "label":"DT1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"da7243ccb59a4302b0fad70b03fd2dcf",
                  "label":"",
                  "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ac1d5f3acf84d0a8c25514727b35ccd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_4/u5.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"03f561e53f694182b6d5ac7e732a42d7",
              "label":"DT2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e69c5dfa5df2474dba2a19c21c27a4d2",
                  "label":"",
                  "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"828b1f4292f2418394a39511eb432c06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_4/u7.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0ccb4d148dcc4c4cb46e3285614e13bf",
              "label":"DT3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f69b59bd8a784118a3d9acb1568a4a48",
                  "label":"",
                  "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9dbfb2d8efa41f4b1e3a0e69cdc3bc3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_4/u9.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4bd72457cb1940fe857fc8650b81945e",
              "label":"DT4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0f4e0b12c30040388510d4ecebc0f1af",
                  "label":"",
                  "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":289}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf0e6d386c8046b2a4216e9c28613870",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f9ebedf4ce7c4c928d02b8af8c0862f3",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":289}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/detail_4/u11.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e18bda1e39114b8285876adbba3b2d23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":419},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5726ae6ae79f4cc197178c2a4cb7f756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":419},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/detail_4/u13.png"}},
{
          "id":"fccafe2cf7e247f6a95ead84b2285a77",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":399},
            "size":{
              "width":563,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/detail_1/u15_line.png"}},
{
          "id":"03c31089d9564f99bd579beb85681950",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":423},
            "size":{
              "width":200,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4829628d8dbe4b3b96be6656e93cf91d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":423},
                "size":{
                  "width":200,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9e8f46def1844e59ec31700eec114bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":529},
            "size":{
              "width":510,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f8a0994772247979e1a7ec5a8a8ffc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":529},
                "size":{
                  "width":510,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee3eaaa13ae14855a1869e61d3b8dd2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":719},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7cff79ba4154d0e877b69739b4972d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":719},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=py2yz.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=py2yz.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"10bb2ec2be4b4e33aba64e495239d42c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":780},
            "size":{
              "width":640,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e829b21c59841e793f48417534fc42e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":780},
                "size":{
                  "width":640,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u34.png"}},
{
          "id":"26f8634388b947af820d4146b5cb2b9f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":32,
              "y":809},
            "size":{
              "width":577,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d7e398f277460daa2b10d6ba438b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":32,
                  "y":809},
                "size":{
                  "width":577,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de3045f6aef74f158c5c489eb15acc20",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":209,
              "y":13},
            "size":{
              "width":220,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69cf4177fba0479e8920a679ee8aedab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":13},
                "size":{
                  "width":220,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"260251fb090b4247aeb1459650b8289b",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseDown":{
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":16,
              "y":10},
            "size":{
              "width":74,
              "height":60},
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b016f5cb3842838210d3fe60f6bf4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseDown":{
                    "outerShadow":{
                      "on":false,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":16,
                  "y":10},
                "size":{
                  "width":74,
                  "height":60},
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/detail_1/button_u24.png",
            "mouseDown~":"images/detail_1/button_u24_mouseDown.png"}},
{
          "id":"b5d4c100a1fa42ec9bbfa804a805ac6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":720},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e02751428c47d79465d2c4a0bf3d51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":720},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_wo.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_wo.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"396b5c6bb33b4f71b89e4bec14f2d305",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":720},
            "size":{
              "width":165,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be6ba8045d21437daf84d11a4b93134a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":720},
                "size":{
                  "width":165,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_ai.apk",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://feimiao.magicbirds.cn/wnsv2/d.do?file=bydr_ai.apk",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4782a96699394f8cabf07f86f51aeadb":{
      "scriptId":"u0"},
    "80f850c5faf74d0fa8540f8f626c7504":{
      "scriptId":"u1"},
    "95f0260c725749f3aeab1c2e931e0d5f":{
      "scriptId":"u2"},
    "ca767d2567a94e4db6614561d9d558ce":{
      "scriptId":"u3"},
    "f9ebedf4ce7c4c928d02b8af8c0862f3":{
      "scriptId":"u4"},
    "da7243ccb59a4302b0fad70b03fd2dcf":{
      "scriptId":"u5"},
    "5ac1d5f3acf84d0a8c25514727b35ccd":{
      "scriptId":"u6"},
    "e69c5dfa5df2474dba2a19c21c27a4d2":{
      "scriptId":"u7"},
    "828b1f4292f2418394a39511eb432c06":{
      "scriptId":"u8"},
    "f69b59bd8a784118a3d9acb1568a4a48":{
      "scriptId":"u9"},
    "b9dbfb2d8efa41f4b1e3a0e69cdc3bc3":{
      "scriptId":"u10"},
    "0f4e0b12c30040388510d4ecebc0f1af":{
      "scriptId":"u11"},
    "bf0e6d386c8046b2a4216e9c28613870":{
      "scriptId":"u12"},
    "e18bda1e39114b8285876adbba3b2d23":{
      "scriptId":"u13"},
    "5726ae6ae79f4cc197178c2a4cb7f756":{
      "scriptId":"u14"},
    "fccafe2cf7e247f6a95ead84b2285a77":{
      "scriptId":"u15"},
    "03c31089d9564f99bd579beb85681950":{
      "scriptId":"u16"},
    "4829628d8dbe4b3b96be6656e93cf91d":{
      "scriptId":"u17"},
    "d9e8f46def1844e59ec31700eec114bf":{
      "scriptId":"u18"},
    "7f8a0994772247979e1a7ec5a8a8ffc9":{
      "scriptId":"u19"},
    "ee3eaaa13ae14855a1869e61d3b8dd2c":{
      "scriptId":"u20"},
    "f7cff79ba4154d0e877b69739b4972d1":{
      "scriptId":"u21"},
    "10bb2ec2be4b4e33aba64e495239d42c":{
      "scriptId":"u22"},
    "9e829b21c59841e793f48417534fc42e":{
      "scriptId":"u23"},
    "26f8634388b947af820d4146b5cb2b9f":{
      "scriptId":"u24"},
    "11d7e398f277460daa2b10d6ba438b9a":{
      "scriptId":"u25"},
    "de3045f6aef74f158c5c489eb15acc20":{
      "scriptId":"u26"},
    "69cf4177fba0479e8920a679ee8aedab":{
      "scriptId":"u27"},
    "260251fb090b4247aeb1459650b8289b":{
      "scriptId":"u28"},
    "b9b016f5cb3842838210d3fe60f6bf4c":{
      "scriptId":"u29"},
    "b5d4c100a1fa42ec9bbfa804a805ac6a":{
      "scriptId":"u30"},
    "a0e02751428c47d79465d2c4a0bf3d51":{
      "scriptId":"u31"},
    "396b5c6bb33b4f71b89e4bec14f2d305":{
      "scriptId":"u32"},
    "be6ba8045d21437daf84d11a4b93134a":{
      "scriptId":"u33"}}});